# @hostname = 127.0.0.1
# @port = 3000
@host = {{hostname}}:{{port}}
@baseUrl = http://{{host}}

###

GET {{baseUrl}}/hello?name=Xenia HTTP/1.1
content-type: application/json

###
# @name Login

POST {{baseUrl}}/auth/login HTTP/1.1
content-type: application/json

{
    "email": "demo",
    "password": "test"
}

###

@authCookie = {{Login.response.headers.set-cookie}}

GET {{baseUrl}}/tickets HTTP/1.1
# Cookie: {{authCookie}}

###

@authCookie = {{Login.response.headers.set-cookie}}

POST {{baseUrl}}/tickets HTTP/1.1
content-type: application/json

{
    "title": "demo ticket 123"
}